# Site settings
title: HuiYe123
description: 欢迎来到Huiye123的世界
baseurl: "huiye123.cn" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://huiyebaby.github.io"  


# GitHub User settings
username: HuiYe123
github_username: HuiyeBaby
user_description: 一个喜欢钻研技术的老咸鱼
user_title: HuiyeBaby
email: huiye123cn@Gmail.com

# Blog Author settings
author:
  name:            
  picture:        
  email:           
  description:     
  twitter:
  facebook:
  github:          
  linkedin:
  clustrmap:      


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
